### ISSUE TITLE
Feature request - ability to have chkbit continue after error(s)

### ISSUE THREAD

**Issue by aubloom** [laktak/chkbit-js#1]
I’ve been trying out chkbit on several Mac OS X (Yosemite) volumes. What I’d like is a way to have the program continue to scan files after hitting an error. Then I could search the transcript afterwards to identify the trouble spots, knowing the rest of the drive had been checked. Currently an error stops the whole process and then the Terminal prompt reappears. This makes it too hard to get through an initial scan.

When I say error, I don’t mean a hash error, as I’m just trying to generate the hashes for the first time on the volume, but sometimes chkbit encounters package files or directories that are locked (a Mac-only thing) or it encounters package files or directories with mixed permissions (e.g. read-only) and is then unable to write an index file inside them. Either of these conditions ends the process.

Thanks much.

**Comment by laktak** [comment]
Please take a look at the latest master. I'll update npm if it works for you.

**Comment by aubloom** [comment]
Thanks a lot for looking into this. Sorry, I need to ask how to install/try out the fix version. This is my first time on github and only my second time using npm.

**Comment by laktak** [comment]
You probably don't have git so just download the zip [(here)](https://github.com/laktak/chkbit).

Then run `npm i -g ~/Downloads/chkbit-master/`(or where you downloaded & extracted it)

It should print `chkbit@1.3.0`

**Comment by aubloom** [comment]
Thanks for pointing out the zip.

OK, so I've done some tests with 1.3. It was able to ignore locked directories and files and continue checking which 1.2 cannot.

However, when 1.3 hit one peculiar error ("no such file or directory, stat 'Users/John/Library/Saved Application State/com.apple.Preview.savedState") that did kill the process. This is a library file in a User folder in Mac OS X. It may have some irregular status assigned it by the OS, but by that definition, it is again the kind I think most users would be happy to have chkbit skip past, since its an OS maintenance file. Obviously it would be most convenient to be able to run chkbit on a User folder.

**Comment by laktak** [comment]
I fixed it but let me know if you find any other issues. You can install from npm.

Usually you wouldn't let it check your whole drive though (see [FAQ](https://github.com/laktak/chkbit#faq)). It's meant for folders that contain your archives (pictures/videos/documents/etc.).

**Comment by aubloom** [comment]
Thanks again. And also, you're right. I'm trying to work out a more moderate approach to using the program. It's probably my unfamiliarity with scripting/automation that makes it tedious for me to isolate sections of the hard drive for checking, but that's what I need to do.
