### ISSUE TITLE
ENFILE and EMFILE errors

### ISSUE THREAD

**Issue by farmerchris** [laktak/chkbit-js#2]
I am seeing a lot ENFILE errors and sometimes EMFILE errors that are reported in various ways by chkbit.

```
E Photos Library.photoslibrary/Thumbnails/2014/09/14/20140914-024930/.chkbit damaged (force to repair)
E Photos Library.photoslibrary/Thumbnails/2014/09/14/20140914-115554/.chkbit damaged (force to repair)
E Photos Library.photoslibrary/Thumbnails/2014/09/15/20140915-032445/.chkbit damaged (force to repair)
E Photos Library.photoslibrary/Thumbnails/2014/09/15/20140915-120525/.chkbit damaged (force to repair)
E Photos Library.photoslibrary/Thumbnails/2014/09/16/20140916-034340/.chkbit damaged (force to repair)
E Photos Library.photoslibrary/Thumbnails/2014/09/17/20140917-220434/.chkbit damaged (force to repair)
Error: ENFILE: file table overflow, scandir 'Photos Library.photoslibrary/Thumbnails/2014/07/07/20140707-000617'

Can't write Google Photos Backup/.chkbit
e Can't write Google Offload/.chkbit
e Can't write Old Photos Libraries/.chkbit
e Can't write Photos Library.photoslibrary/.chkbit
Error: ENFILE: file table overflow, uv_cwd
```

This seems to occur when I run chkbit in directories with a lot of files.  The note in source about updating to node 0.12+ doesn't seem to help as I am on node 6.2.2:

```
$ node --version 
v6.2.2
$ uname -a
Darwin <hostname> 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
$ python --version
Python 2.7.12
```

Is there any way around this error? Is a file descriptor leaking?

Thanks!

**Comment by farmerchris** [comment]
This seems to happen when I have a very large directory tree, with thousands of subdirectories. The Pictures folder on my Mac is a good example. Photos creates a very deep directory structure under the .photoslibrary root, with a directory for every single day that a photo was taken and hundreds of resource directories.

Chkbit seems to open up the .chkbit file in each subdirectory simultaneously. With enough subdirectories, this runs against the system limit of files per process or files systemwide.

Would it be possible to queue these operations to conserve file descriptors?

**Comment by laktak** [comment]
chkbit already contained a limiter which I enabled for reading the index file as well. Please let me know if this fixes your issue.

**Comment by farmerchris** [comment]
At first glance this seem to fix the problem. If you run "sysctl kern.num_files" now the result stays pretty constant. With the old version it skyrocketed until there was an overflow. Thanks! I will have to figure out this Promise pattern to understand the fix - I haven't worked with Node much yet.
