### ISSUE TITLE
Including files and directories that begin with a dot.

### ISSUE THREAD

**Issue by MarkJerde** [laktak/chkbit-js#5]
Thank you for developing chkbit.  I like it a lot.  I noticed that files and directories that begin with a dot (".") are not included.  This causes files like .bashrc and directories like the .git directory in a repository to be missed.  I tweaked lib/chkbit.js to only exclude ".chkbit" (of course), ".", "..", and anything that starts with "~".  Before I roll it into a pull request, would you prefer that this always use this new filtering or conditional between the new and old?  If conditional, which would you prefer to be the default?

Since inclusion of dot files lends itself to more files that might want to be ignored, what are your feelings on me adding support for a global .checkbitignore file in the users home directory?  I assume this is preferable to hard coding in things like ".DS_Store" (Mac stuff) and ".dropbox" in lib/chkbit.js.

Thanks again!
Mark

**Comment by laktak** [comment]
Closing for #6
